fix(deps): Bump org.jetbrains.dokka from 1.7.10 to 1.8.20 (#119)
Bumps [org.jetbrains.dokka](https://github.com/Kotlin/dokka) from 1.7.10 to 1.8.20.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/Kotlin/dokka/releases">org.jetbrains.dokka's releases</a>.</em></p>
<blockquote>
<h2>1.8.10 Beta</h2>
<p>Dokka's documentation has been entirely rewritten and can now be found on <a href="https://kotlinlang.org/docs/dokka-introduction.html">kotlinlang.org</a>:</p>
<ul>
<li>More examples, including Groovy DSL for Gradle project configuration</li>
<li>More guidelines to help beginners</li>
<li>More details for complex projects</li>
</ul>
<p><strong>Note</strong>: Version 1.8.0 was skipped due to a Metaspace memory leak in Kotlin's reflection (<a href="https://youtrack.jetbrains.com/issue/KT-56093">KT-56093</a>). Dokka 1.8.10 should be fully compatible with Kotlin 1.8.0.</p>
<h2>Improvements</h2>
<ul>
<li>Revise project documentation and examples (<a href="https://redirect.github.com/Kotlin/dokka/issues/2728">#2728</a>, <a href="https://redirect.github.com/Kotlin/dokka/issues/2737">#2737</a>, <a href="https://redirect.github.com/Kotlin/dokka/issues/2736">#2736</a>). Thanks to <a href="https://github.com/sarahhaggarty"><code>@​sarahhaggarty</code></a> for helping!</li>
<li>Support generating documentation for Kotlin/Wasm projects (<a href="https://redirect.github.com/Kotlin/dokka/issues/2814">#2814</a>). Thanks to <a href="https://github.com/igoriakovlev"><code>@​igoriakovlev</code></a>!</li>
<li>Move the contents of <code>Inheritors</code>, <code>Parameters</code>, <code>See also</code> and <code>Samples</code> tabs into the main declaration description (<a href="https://redirect.github.com/Kotlin/dokka/issues/2688">#2688</a>).</li>
<li>Add <code>Members</code> and <code>Members &amp; Extensions</code> tabs to class-like declaration pages (<a href="https://redirect.github.com/Kotlin/dokka/issues/2764">#2764</a>).</li>
<li>Display source set / platform indicators at all times, which should help identify the supported platform of single-platform libraries and modules. (<a href="https://redirect.github.com/Kotlin/dokka/issues/2847">#2847</a>).</li>
<li>Generate the default no-arg constructor for Java declarations (<a href="https://redirect.github.com/Kotlin/dokka/issues/2765">#2765</a>).</li>
</ul>
<h2>Bugfixes</h2>
<ul>
<li>Fixed analysis environment not being properly disposed (<a href="https://redirect.github.com/Kotlin/dokka/issues/2755">#2755</a>).</li>
<li>Fixed nondeterministic sorting of function/property overloads (<a href="https://redirect.github.com/Kotlin/dokka/issues/2784">#2784</a>).</li>
<li>Fixed inconsistent alphabetical order of element groups in index and navigation (<a href="https://redirect.github.com/Kotlin/dokka/issues/2861">#2861</a>).</li>
<li>Fixed constructors being rendered as functions (<a href="https://redirect.github.com/Kotlin/dokka/issues/2689">#2689</a>).</li>
<li>Fixed default values for <code>var</code> properties being displayed (<a href="https://redirect.github.com/Kotlin/dokka/issues/2717">#2717</a>).</li>
<li>Fixed source links leading to the KDoc instead of the declaration (<a href="https://redirect.github.com/Kotlin/dokka/issues/2724">#2724</a>).</li>
<li>Fixed thread-safety issues in <code>DokkaLogger</code> (<a href="https://redirect.github.com/Kotlin/dokka/issues/2827">#2827</a>).</li>
<li>Fixed documentation not being inherited in case of diamond inheritance (<a href="https://redirect.github.com/Kotlin/dokka/issues/2686">#2686</a>).</li>
</ul>
<h3>Gradle Plugin</h3>
<ul>
<li>Fixed <code>NoSuchMethodError</code> when running under Gradle 8 (<a href="https://redirect.github.com/Kotlin/dokka/issues/2796">#2796</a>).</li>
<li>Fixed possible metaspace leaks due to external thread locals not being disposed (<a href="https://redirect.github.com/Kotlin/dokka/issues/2678">#2678</a>).</li>
<li>Fixed premature initialization of <code>outputDirectory</code> input property (<a href="https://redirect.github.com/Kotlin/dokka/issues/556">#556</a>).</li>
<li>Fixed premature initialization of <code>moduleVersion</code> input property (<a href="https://redirect.github.com/Kotlin/dokka/issues/2799">#2799</a>). Thanks to <a href="https://github.com/JavierSegoviaCordoba"><code>@​JavierSegoviaCordoba</code></a>!</li>
<li>Fixed unnecessary snapshotting of source link directory input which led to performance problems (<a href="https://redirect.github.com/Kotlin/dokka/issues/2807">#2807</a>).</li>
<li>Fixed missing group and description for <code>MultiModule</code> tasks (<a href="https://redirect.github.com/Kotlin/dokka/issues/2806">#2806</a>). Thanks to <a href="https://github.com/TWiStErRob"><code>@​TWiStErRob</code></a>!</li>
</ul>
<h3>Javadoc</h3>
<ul>
<li>Fixed truncation of module and package description after the first sentence (<a href="https://redirect.github.com/Kotlin/dokka/issues/2055">#2055</a>). Thanks to <a href="https://github.com/BlackAnubis7"><code>@​BlackAnubis7</code></a>!</li>
<li>Fixed rendering of empty/useless Kotlin companion objects (<a href="https://redirect.github.com/Kotlin/dokka/issues/200">#200</a>, <a href="https://redirect.github.com/Kotlin/dokka/issues/2086">#2086</a>)</li>
<li>Fixed leaking configuration/environment details in generated links (<a href="https://redirect.github.com/Kotlin/dokka/issues/2803">#2803</a>).</li>
<li>Fixed incorrect links when <code>javadoc.jar</code> produced by Dokka is imported into IntelliJ IDEA / Android Studio (<a href="https://redirect.github.com/Kotlin/dokka/issues/2734">#2734</a>). Thanks to <a href="https://github.com/bomberaya"><code>@​bomberaya</code></a>!</li>
</ul>
<h2>Plugin API</h2>
<ul>
<li>Mark Plugin API as experimental (<a href="https://redirect.github.com/Kotlin/dokka/issues/2716">#2716</a>).</li>
</ul>
<h2>Infrastructure</h2>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li>See full diff in <a href="https://github.com/Kotlin/dokka/commits">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.jetbrains.dokka&package-manager=gradle&previous-version=1.7.10&new-version=1.8.20)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)


</details>